### ISSUE TITLE
Return a promise

### ISSUE THREAD

**Issue by Tubaleviao** [alessioalex/get-folder-size#15]
I guess it would be great to return a promise so we can use async/await.

**Comment by alessioalex** [comment]
True that, will be done soon.

**Comment by atjn** [comment]
@alessioalex would you like some help on this? I need async support in a project and I would much rather fix it upstream than do something funky in our codebase.

I was thinking of jumping to v3.0.0 and replacing the callback mechanism with es6 import modules and async/await. If anyone needs the older syntax, they can simply stay on v2. This is obviously a major overhaul, so I can understand if you'd rather do it yourself :)

**Comment by alessioalex** [comment]
@atjn I would welcome any support for that, thank you very much!

**Comment by atjn** [comment]
Cool, I will get started on it :)

Quick question - [should.js](https://github.com/shouldjs/should.js) is no longer maintained and I don't want to write a bunch of tests in a syntax that will have to be refactored in the near future. Do you mind if I write the tests with [TAP](https://node-tap.org/) instead?

**Comment by atjn** [comment]
I'll take my chances and guess that you're okay with it ;)

**Comment by alessioalex** [comment]
Thank you for your effort! Will take a look at the pull request today!

**Comment by alessioalex** [comment]
@atjn I've merged into master and will publish the new version to NPM now. Also invited you as a collaborator so in case you want to you could make updates to the code directly. Could you tell me your npm username so that you can also push new versions there directly?

**Comment by atjn** [comment]
@alessioalex happy I could help!
I would love to be able to make changes directly, although I can't make any guarantees for how active I will be. My username on npm is also [atjn](https://www.npmjs.com/~atjn) :)

**Comment by alessioalex** [comment]
No problem, it's just fair that since you rewrote the whole thing you should be able to update it anytime you want. Thanks again for the big help!

**Comment by Tubaleviao** [comment]
Thanks @atjn ! I like that you wrote some tests as well, that was pretty awesome!
