### ISSUE TITLE
Number overflow

### ISSUE THREAD

**Issue by wholegroup** [alessioalex/get-folder-size#21]
Hi,

https://github.com/alessioalex/get-folder-size/blob/f5c7a3f5486cada76b00f4e22773b788b0baa446/index.js#L59-L61

We've got an issue with folder size calculation. We found out that stats.ino can be a BigInt when fs.lstat has additional options parameter.
I have 2 different files, one has ino = 57420895249767887n, the other has ino = 57420895249767888n
But after we cast BigInt to Number we could have the same result for 2 different values.
`Number(57420895249767887n)` is equal to `57420895249767890`
and
`Number(57420895249767888n)` is equal to `57420895249767890` as well

Well, we have wrong size (results can be various because of `Promise.all`) if we call `fs.lstat` without `{bigint: true}` option.

Our current workaround:
```js
  const patchedFs = {...fs};
  patchedFs.lstat = async function (itemPath) {
    const stats = await fs.lstat(itemPath, { bigint: true });
    stats.ino = stats.ino.toString();
    stats.size = Number(stats.size);
    return stats;
  };

  const { size, errors } = await getFolderSize(folder, {
    ignore: /node_modules/,
    fs: patchedFs
  });
```

**Comment by atjn** [comment]
Thank you for documenting this properly and bringing it to our attention!

We should be releasing a fix for it soon :)
