### ISSUE TITLE
If none of these methods work

### ISSUE THREAD

**Issue by AutismPatient** [alessioalex/get-folder-size#24]
error  in ./node_modules/get-folder-size/index.js

Module parse failed: Unexpected token (60:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   async function processItem(itemPath) {
>     if(options.ignore?.test(itemPath)) return;
|
|     const stats = returnType.strict ? await fs.lstat(itemPath, {bigint: true}) : await fs.lstat(itemPath, {bigint: true}).catch(error => errors.push(error));

 @ ./src/preload.js 15:0-44 488:35-48
 @ multi ./src/preload.js

 ERROR  Build failed with errors.

**Comment by alessioalex** [comment]
This module isn't build for the frontend, Node.js only.

**Comment by AutismPatient** [comment]
it in the Nodejs & Electron

**Comment by atjn** [comment]
I suspect you are using an older version of nodejs or webpack, which does not support optional chaining. I can't help you anymore than that because you have provided 0 details.
