### ISSUE TITLE
Gar no longer supported - can it be replaced?

### ISSUE THREAD

**Issue by Emily1799** [alessioalex/get-folder-size#27]
Gar 1.0.4 produces the warning `npm WARN deprecated gar@1.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.`

It seems like gar is only used once -- it might be simple enough to replace with a different arg parser. Would you accept a PR to fix it?

get-folder-size.js:7 for reference

**Comment by atjn** [comment]
Thanks for letting me know :)
I plan on making some updates to this package soon, and one of the changes will be to remove gar. So you don't need to create a PR for it, unless you really want to.

Until the update is ready, I want to stress that the gar package has been stable for many years without any updates, so there is no immediate danger by continuing to use it.

**Comment by atjn** [comment]
I have released version 5.0.0 with Gar nowhere to be seen :)
