### ISSUE TITLE
executable has DOS line-endings.

### ISSUE THREAD

**Issue by mralexgray** [alessioalex/get-folder-size#3]
to get to work on a mac, i needed to 

    brew install dos2unix

and

    dos2unix $(which get-folder-size)

not very easy / impossible for most people.

**Comment by alessioalex** [comment]
That was unintended from my part. Will push a fix for this soon. Thanks again for opening an issue @mralexgray

**Comment by alessioalex** [comment]
should be fixed now, published version 1.0.0 to npm / @mralexgray
