### ISSUE TITLE
--folder= required argument is superfluous.

### ISSUE THREAD

**Issue by mralexgray** [alessioalex/get-folder-size#4]
Obviously, an argument is needed... so the `--folder=` should just be assumed to be the last (or only) argument .  So...

    ❯ get-folder-size --folder=/www/dir

becomes

    ❯ get-folder-size /www/dir

**Comment by alessioalex** [comment]
Yes that makes sense, will update this soon. Thanks for reporting @mralexgray

**Comment by alessioalex** [comment]
should be implemented now, published version 1.0.0 to npm / @mralexgray
