### ISSUE TITLE
Documentation is ambiguous because it uses the wrong abbreviation (MB) for Megabytes

### ISSUE THREAD

**Issue by asinning** [alessioalex/get-folder-size#6]
"Mb" is the abbreviation for Megabits.  Please use "MB".  The mistake makes the documentation ambiguous.  Empirical testing confirms that get-folder-size returns the size in Bytes, not bits.

Thanks!  Very useful package.

```
> var getSize = require('get-folder-size');
>  
> getSize(myFolder, function(err, size) {
>   if (err) { throw err; }
>  
>   console.log(size + ' bytes');
>   console.log((size / 1024 / 1024).toFixed(2) + ' Mb');
> });
```

**Comment by alessioalex** [comment]
Thank you, fixed that now.
