### ISSUE TITLE
Question: Do you count hardlinks/inodes?

### ISSUE THREAD

**Issue by styfle** [alessioalex/get-folder-size#9]
I found a bug in my own [tool](https://github.com/styfle/packagephobia) that gets the size of a folder just like your package `get-folder-size`.

It looks like `get-folder-size` might suffer from the same [issue](https://github.com/styfle/packagephobia/issues/47).

Are you interested in collaborating?
Note, it might not be backwards compatible.

**Comment by alessioalex** [comment]
@styfle thank you for reporting this and apologies for getting back so late. I will look into this, but any help is much appreciated!

**Comment by styfle** [comment]
Here's [my implementation](https://github.com/styfle/packagephobia/blob/7a285cfccb7bdd76d1792858351e6faa2f9f796c/src/util/backend/npm-stats.ts#L8) as seen in https://github.com/styfle/packagephobia/pull/48

I was going to release as it's own package but I thought I would try to collaborate with the existing ecosystem and found your package.

**Comment by alessioalex** [comment]
Thanks for the tip, seems like a quick fix. I'll be offline until Wednesday, so I'll fix the problem then and release a new version of the module.

**Comment by alessioalex** [comment]
@styfle published version `2.0.0` on npm that contained a fix for this bug. Luckily I didn't have the change the api either. Thanks again for reporting it.

**Comment by styfle** [comment]
Very cool, thanks! 👍
